services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aboutmesite-web
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./database:/app/database
    networks:
      - n8n_default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=n8n_default"
      - "traefik.http.routers.aboutme.rule=Host(`aboutme.dimonrond.ru`)"
      - "traefik.http.routers.aboutme.entrypoints=websecure"
      - "traefik.http.routers.aboutme.tls=true"
      - "traefik.http.routers.aboutme.tls.certresolver=letsencrypt"
      - "traefik.http.services.aboutme.loadbalancer.server.port=5000"

networks:
  n8n_default:
    external: true
